#pragma once

void CheckVmwareFiles();
void CheckVmwareDevices();
void CheckVmwareMac();
void CheckVmwareReg();
void CheckVmwareSMBIOS();
void CheckVmwareACPI();
void CheckVmwareProcesses();
void CheckDiskdrive();
void CheckCPUID();
void CheckBIOSSerialNumberWMI();
void CheckModelComputerSystemWMI();
void CheckManufacturerComputerSystemWMI();
void CheckCPUFanWMI();
void CheckChacheMemoryWMI();
void CheckVoltageProbeWMI();
void CheckThermalZoneInfoWMI();
void CheckCIMMemoryWMI();
void CheckCIMSensorWMI();
void CheckCIMNumericSensorWMI();
void CheckCIMTemperatureSensorWMI();
void CheckCIMVoltageSensorWMI();
void CheckRegServicesDiskEnum();
void CheckRegDiskEnum();
void CheckRdtscDiffVmexit();